// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTFMVU-UmjLvN1RWKW8jwDZ74unwfUXKg',
    appId: '1:874299753823:web:dad8f55ab96254079762ea',
    messagingSenderId: '874299753823',
    projectId: 'kateringku-765be',
    authDomain: 'kateringku-765be.firebaseapp.com',
    storageBucket: 'kateringku-765be.appspot.com',
    measurementId: 'G-HSS2V0G3NP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzzcCBUbVwUcZvKESIhSE_pulDDFxw9AM',
    appId: '1:874299753823:android:f3eb4db9fbffd6d99762ea',
    messagingSenderId: '874299753823',
    projectId: 'kateringku-765be',
    storageBucket: 'kateringku-765be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRcEQVM-AWwiedYhPCS91VHXNnidmCqjE',
    appId: '1:874299753823:ios:91386c89a775179c9762ea',
    messagingSenderId: '874299753823',
    projectId: 'kateringku-765be',
    storageBucket: 'kateringku-765be.appspot.com',
    iosClientId: '874299753823-06utor5ubi0i01b7sdk8u6r8obgf2cul.apps.googleusercontent.com',
    iosBundleId: 'com.example.kateringkuMobile',
  );
}
